language: node_js
node_js:
  - node
install:
  - npm install
before_deploy:
  - npm pack
deploy:
  provider: releases
  api_key:
    secure: p46RXiQ13ZSCOa8rDdUX28qhkesO4xiSOMgyP5ptR5jDUSZM11iByqPTcFgHu5/ID4nPLP+Es7sSV3HR54rP+3knijWQEz3k6r7q40vGFw4TbmA0LY6ihBLwod0VZBtyO9R74hCC+txJ4itycr5kQp+csWYMUvxZdvOwJc1mHM1K7pnZeEXAYmSoYDRuWYwb+0hXDqptvgufv2OOgsKosE4IilH1tH363TOUJWrMyD/C30VnarMafSh+XJuoBqC2AUVEU0+Ey0KWbai6wtda7YS0JCWRQCxWKcTfWLk9vAtirgw6w3UEYrlOL2CB0Q4dnnh9rxeOEeJ4wx36y5nmj0BwwPjK/EIlkwv+V3Qb4Ifh2tlUDO13L8Aqu5UDovVOfMIcPJ1e2F2BJNpXMhGyqkWVJwR44BHVPUFcVkFI+zC/ZHJlZGnESCWz9/WuSr4OH3N51aKYgqy+5GJP4X5aIz10ZtMUIemocj/jtcJxQj01Ah6TNWiPBzQkmuS7xKx1fZ9AHy+s5Mc3kHkBR/k/PfpGBI+i+6zBSeSGJSXqMGWVkt6E1h6CYQgRHvMBsZRtN2RhDJZQ+J5LNk3qqtkW6kMoMPnr2PYJncnZh1PXW5NOGKRdt07MjsFud2XPtFkIR8nJaHu2+ucUiIc8BFhO66hQGsqMaZaCBIYjNN5M3oE=
  file: LogTailer-0.0.2.tgz
  on:
    repo: St-Ex/logTailer
